version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8081:80"
    networks:
      - portfolio-network

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    environment:
      - APP_ENV=production
    ports:
      - "8082:80"
    networks:
      - portfolio-network

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge