version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    networks:
      - portfolio-network

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    environment:
      - APP_ENV=production
    volumes:
      - ./backend:/var/www/html
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge