version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    environment:
      - APP_ENV=production

networks:
  default:
    driver: bridge  
    name: portfolio-network