version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    networks:
      - portfolio-network
    ports:
      - "3001:80"
    restart: always

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    networks:
      - portfolio-network
    ports:
      - "9001:9000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=production
    restart: always


networks:
  portfolio-network:
    driver: bridge
