version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    environment:
      - APP_ENV=production

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

networks:
  default:
    name: portfolio-network