name: Docker Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker
        run: |
          sudo groupadd docker || true
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            if [ -d "/root/portfolio/.git" ]; then
              cd /root/portfolio
              git fetch origin
              git reset --hard origin/master
            else
              git clone https://github.com/kamiql/portfolio.git /root/portfolio
              cd /root/portfolio
            fi
            
            # Add Docker permissions
            sudo usermod -aG docker $USER
            newgrp docker
            
            # Run deployment script
            chmod +x deploy.sh
            bash deploy.sh